#if !defined(HTTP_SERVER_TASK_COMMON__H)
#define HTTP_SERVER_TASK_COMMON__H

#define WIFI_APP_TASK_STACK_SIZE 4096
#define WIFI_APP_TASK_PRIORITY 5
#define WIFI_APP_TASK_CORE_ID 0

#define HTTP_SERVER_TASK_STACK_SIZE 4096
#define HTTP_SERVER_TASK_PRIORITY 4
#define HTTP_SERVER_TASK_CORE_ID 0

#define HTTP_SERVER_MONITOR_STACK_SIZE 4096
#define HTTP_SERVER_MONITOR_PRIORITY 3
#define HTTP_SERVER_MONITOR_CORE_ID 0

#endif // HTTP_SERVER_TASK_COMMON__H
