#if !defined(TASK_COMMON__H)
#define TASK_COMMON__H

#define WIFI_APP_TASK_STACK_SIZE 4096
#define WIFI_APP_TASK_PRIORITY 5
#define WIFI_APP_CORE_ID 0

#define BLINK_TASK_STACK_SIZE 4096
#define BLINK_TASK_PRIORITY tskIDLE_PRIORITY
#define WIFI_APP_CORE_ID 0

#endif // TASK_COMMON__H
